export const MINIFIER_UNAVAILABLE_MESSAGE =
  "HTML minifier could not be loaded. Your HTML was left unchanged. Reinstall the app or restore frontend/tools/html-editor/vendor/htmlminifier.min.js.";

export const MINIFIER_INVALID_RESULT_MESSAGE = "HTML minifier returned an invalid result. Your HTML was left unchanged.";

export const MINIFIER_OPTIONS = {
  caseSensitive: false,
  collapseBooleanAttributes: false,
  collapseInlineTagWhitespace: true,
  collapseWhitespace: true,
  conservativeCollapse: false,
  decodeEntities: false,
  html5: true,
  includeAutoGeneratedTags: false,
  keepClosingSlash: false,
  minifyCSS: true,
  minifyJS: true,
  preserveLineBreaks: false,
  preventAttributesEscaping: false,
  processConditionalComments: true,
  processScripts: ["text/html"],
  removeAttributeQuotes: false,
  removeComments: true,
  removeEmptyAttributes: false,
  removeEmptyElements: false,
  removeOptionalTags: false,
  removeRedundantAttributes: false,
  removeScriptTypeAttributes: false,
  removeStyleLinkTypeAttributes: false,
  removeTagWhitespace: false,
  sortAttributes: false,
  sortClassName: false,
  trimCustomFragments: false,
  useShortDoctype: false,
};

export function parseCdnPackageInfo(minifierSource = "") {
  const src = typeof minifierSource === "string" ? minifierSource : "";
  const name = "html-minifier";
  const m1 = src.match(/html-?minifier\s*v(\d+\.\d+\.\d+)/i);
  const m2 = src.match(/@version\s*([0-9]+\.[0-9]+\.[0-9]+)/i);
  const version = (m1 && m1[1]) || (m2 && m2[1]) || null;
  const npmUrl = version ? `https://www.npmjs.com/package/${name}/v/${version}` : `https://www.npmjs.com/package/${name}`;
  return { name, version, npmUrl };
}

export function loadHtmlMinifier(minifierSource, scope = globalThis) {
  if (!minifierSource || typeof minifierSource !== "string") {
    return null;
  }

  try {
    const factory = new Function(
      "self",
      `
let require;
const window = self;
const globalThis = self;
${minifierSource}
const htmlMinifierModule = require("html-minifier");
return htmlMinifierModule && htmlMinifierModule.minify;
`,
    );
    const candidate = factory.call(scope, scope);
    return typeof candidate === "function" ? candidate : null;
  } catch (_err) {
    return null;
  }
}

export function normalizeMinifiedHtml(result) {
  if (typeof result !== "string") {
    throw new Error(MINIFIER_INVALID_RESULT_MESSAGE);
  }
  return result.replace(/\r?\n+/g, "");
}
