// HTML Minifier vendored browser build (CDN download)
import minifierSource from "./vendor/htmlminifier.min.js?raw";
let minifyFn = null;

const MINIFIER_UNAVAILABLE_MESSAGE =
  "HTML minifier is unavailable. Reinstall dependencies with npm install html-minifier or npm install, then restart the app.";

function parseCdnPackageInfo() {
  const src = typeof minifierSource === "string" ? minifierSource : "";
  const name = "html-minifier";
  let version = null;
  // Try common patterns in the vendored CDN header
  const m1 = src.match(/html-minifier\s*v(\d+\.\d+\.\d+)/i);
  const m2 = src.match(/@version\s*([0-9]+\.[0-9]+\.[0-9]+)/i);
  version = (m1 && m1[1]) || (m2 && m2[1]) || null;
  const npmUrl = version ? `https://www.npmjs.com/package/${name}/v/${version}` : `https://www.npmjs.com/package/${name}`;
  return { name, version, npmUrl };
}

async function ensureMinifierLoaded() {
  if (minifyFn) return true;
  try {
    if (minifierSource && typeof minifierSource === "string" && minifierSource.length > 0) {
      const factory = new Function(
        minifierSource +
          '\nreturn (typeof require==="function" ? require("html-minifier") : (self.minify || (self.htmlMinifier && self.htmlMinifier.minify) || null));',
      );
      const mod = factory();
      const candidate = (mod && mod.minify) || mod;
      if (typeof candidate === "function") {
        minifyFn = candidate;
        return true;
      }
    }
  } catch (e) {
    // Surface a single actionable message to the UI below.
  }
  return false;
}

// Options matching your desired configuration
const OPTIONS = {
  caseSensitive: false,
  collapseBooleanAttributes: false,
  collapseInlineTagWhitespace: true,
  collapseWhitespace: true,
  conservativeCollapse: false,
  decodeEntities: false,
  html5: true,
  includeAutoGeneratedTags: false,
  keepClosingSlash: false,
  minifyCSS: true,
  minifyJS: true,
  preserveLineBreaks: false,
  preventAttributesEscaping: false,
  processConditionalComments: true,
  processScripts: ["text/html"],
  removeAttributeQuotes: false,
  removeComments: true,
  removeEmptyAttributes: false,
  removeEmptyElements: false,
  removeOptionalTags: false,
  removeRedundantAttributes: false,
  removeScriptTypeAttributes: false,
  removeStyleLinkTypeAttributes: false,
  removeTagWhitespace: false,
  sortAttributes: false,
  sortClassName: false,
  trimCustomFragments: false,
  useShortDoctype: false,
};

self.onmessage = async (e) => {
  const type = e?.data?.type || "minify";
  const html = e?.data?.html ?? "";
  try {
    if (type === "probe") {
      const loaded = await ensureMinifierLoaded();
      const details = loaded ? parseCdnPackageInfo() : null;
      self.postMessage({
        type: "probe",
        success: loaded,
        error: loaded ? null : MINIFIER_UNAVAILABLE_MESSAGE,
        engine: loaded ? "html-minifier" : null,
        enginePackageName: details?.name || null,
        enginePackageVersion: details?.version || null,
        enginePackageUrl: details?.npmUrl || null,
      });
      return;
    }
    const loaded = await ensureMinifierLoaded();
    if (!loaded) {
      self.postMessage({ type: "minify", success: false, error: MINIFIER_UNAVAILABLE_MESSAGE });
      return;
    }

    const details = loaded ? parseCdnPackageInfo() : null;
    let result = minifyFn(html, OPTIONS);
    result = typeof result === "string" ? result.replace(/\r?\n+/g, "") : "";
    self.postMessage({
      type: "minify",
      success: true,
      result,
      engine: "html-minifier",
      enginePackageName: details?.name || null,
      enginePackageVersion: details?.version || null,
      enginePackageUrl: details?.npmUrl || null,
    });
  } catch (err) {
    self.postMessage({ success: false, error: err?.message || String(err) });
  }
};
