export const LIVIN_FN_COMPLETIONS = [
  {
    label: "$fn.now()",
    insertText: "$fn.now()",
    detail: "Livin date helper",
    documentation: "Current date using the default backend format. Registry: currentDate.",
  },
  {
    label: "$fn.now(format)",
    insertText: '$fn.now("${1:yyyy-MM-dd}")',
    detail: "Livin date helper",
    documentation: "Current date using a custom Java date format. Registry: currentDate.",
  },
  {
    label: "$fn.timestampFromMillis()",
    insertText: "$fn.timestampFromMillis()",
    detail: "Livin timestamp helper",
    documentation: "Current timestamp from milliseconds. Registry: timestampMillis.",
  },
  {
    label: "$fn.timestampFromMillis(longMillis)",
    insertText: '$fn.timestampFromMillis("${1:1700000000000}")',
    detail: "Livin timestamp helper",
    documentation: "Timestamp from a millisecond value. Registry: timestampMillis.",
  },
  {
    label: "$fn.currentSystemTimeMillis()",
    insertText: "$fn.currentSystemTimeMillis()",
    detail: "Livin timestamp helper",
    documentation: "Current system time in milliseconds. Registry: currentSystemTimeMillis.",
  },
  {
    label: "$fn.getLocalDate()",
    insertText: "$fn.getLocalDate()",
    detail: "Livin date helper",
    documentation: "Current local date. Registry: localDateFunction.",
  },
  {
    label: "$fn.getLocalDate(yyyyMMdd)",
    insertText: '$fn.getLocalDate("${1:20260513}")',
    detail: "Livin date helper",
    documentation: "Parse a yyyyMMdd value into LocalDate. Registry: localDateFunction.",
  },
  {
    label: "$fn.convertTimestampToStringFormat(timestamp, format)",
    insertText: '$fn.convertTimestampToStringFormat("${1:timestamp}", "${2:yyyy-MM-dd HH:mm:ss}")',
    detail: "Livin timestamp formatter",
    documentation: "Format a timestamp string. Registry: convertTimestampToStringFormat.",
  },
  {
    label: "$fn.getTellerIdStatic()",
    insertText: "$fn.getTellerIdStatic()",
    detail: "Livin teller helper",
    documentation: "Get static teller id data. Registry: tellerId.",
  },
  {
    label: "$fn.getTellerIdDynamic()",
    insertText: "$fn.getTellerIdDynamic()",
    detail: "Livin teller helper",
    documentation: "Get dynamic teller id data. Registry: tellerId.",
  },
  {
    label: "$fn.getTrackingId()",
    insertText: "$fn.getTrackingId()",
    detail: "Livin id helper",
    documentation: "Generate tracking id. Registry: trackingId.",
  },
  {
    label: "$fn.getRunningNumber()",
    insertText: "$fn.getRunningNumber()",
    detail: "Livin running number helper",
    documentation: "Generate default running number. Registry: runningNumber.",
  },
  {
    label: "$fn.getRunningNumber(key, min, max, padding)",
    insertText: '$fn.getRunningNumber("${1:key}", ${2:1}, ${3:999999}, ${4:6})',
    detail: "Livin running number helper",
    documentation: "Generate running number with range and padding. Registry: runningNumber.",
  },
  {
    label: "$fn.convertDateTimeFormat(value, fromFormat, toFormat)",
    insertText: '$fn.convertDateTimeFormat("${1:dateTime}", "${2:yyyy-MM-dd HH:mm:ss}", "${3:dd-MM-yyyy HH:mm:ss}")',
    detail: "Livin date-time formatter",
    documentation: "Convert date-time string between formats. Registry: dateTimeFormatConverter.",
  },
  {
    label: "$fn.convertEpochToDateTimeFormat(epochTime, toFormat)",
    insertText: '$fn.convertEpochToDateTimeFormat("${1:1700000000}", "${2:yyyy-MM-dd HH:mm:ss}")',
    detail: "Livin epoch formatter",
    documentation: "Convert epoch time to formatted date-time. Registry: epochConverter.",
  },
  {
    label: "$fn.getLocalDateTime()",
    insertText: "$fn.getLocalDateTime()",
    detail: "Livin date-time helper",
    documentation: "Current local date-time. Registry: localDateTime.",
  },
  {
    label: "$fn.getLocalDateTime(zoneId)",
    insertText: '$fn.getLocalDateTime("${1:Asia/Jakarta}")',
    detail: "Livin date-time helper",
    documentation: "Current local date-time for a zone id. Registry: localDateTime.",
  },
  {
    label: "$fn.convertDateFormat(value, fromFormat, toFormat)",
    insertText: '$fn.convertDateFormat("${1:date}", "${2:yyyy-MM-dd}", "${3:dd-MM-yyyy}")',
    detail: "Livin date formatter",
    documentation: "Convert date string between formats. Registry: dateFormatConverter.",
  },
  {
    label: "$fn.throwError(type, code, message)",
    insertText: '$fn.throwError("${1:errorType}", "${2:errorCode}", "${3:errorMessage}")',
    detail: "Livin error helper",
    documentation: "Throw backend template error. Registry: throwError.",
  },
  {
    label: "$fn.parseInteger(value)",
    insertText: '$fn.parseInteger("${1:123}")',
    detail: "Livin number helper",
    documentation: "Parse string into integer. Registry: integerParser.",
  },
  {
    label: "$fn.parseBigDecimal(value)",
    insertText: '$fn.parseBigDecimal("${1:123.45}")',
    detail: "Livin number helper",
    documentation: "Parse string into BigDecimal. Registry: bigDecimalParser.",
  },
  {
    label: "$fn.roundingDecimal(value, scale, rounding)",
    insertText: '$fn.roundingDecimal("${1:123.456}", "${2:2}", "${3:HALF_UP}")',
    detail: "Livin number helper",
    documentation: "Round decimal value. Registry: roundingDecimal.",
  },
  {
    label: "$fn.amountFormatter(value, pattern)",
    insertText: '$fn.amountFormatter("${1:123456.78}", "${2:#,##0.00}")',
    detail: "Livin amount formatter",
    documentation: "Format amount with optional pattern. Registry: amountFormatter.",
  },
  {
    label: "$fn.aritmaticUnary(operator, value, rounding)",
    insertText: '$fn.aritmaticUnary("${1:abs}", "${2:value}", "${3:HALF_UP}")',
    detail: "Livin arithmetic helper",
    documentation: "Unary arithmetic operation. Operators include abs, ceil, money, rate, zero, round, roundup. Registry: aritmaticFunction.",
  },
  {
    label: "$fn.aritmaticBinary(operator, value1, value2, rounding)",
    insertText: '$fn.aritmaticBinary("${1:add}", "${2:value1}", "${3:value2}", "${4:HALF_UP}")',
    detail: "Livin arithmetic helper",
    documentation: "Binary arithmetic operation. Operators include add, sub, mul, div. Registry: aritmaticFunction.",
  },
  {
    label: "$fn.aritmaticCompare(operator, value1, value2)",
    insertText: '$fn.aritmaticCompare("${1:gt}", "${2:value1}", "${3:value2}")',
    detail: "Livin arithmetic helper",
    documentation: "Comparison arithmetic operation. Operators include gt, lt, eq. Registry: aritmaticFunction.",
  },
  {
    label: "$fn.convertJsonString(json)",
    insertText: "$fn.convertJsonString(${1:json})",
    detail: "Livin JSON helper",
    documentation: "Convert JSON object/value to string. Registry: jsonToStringConverter.",
  },
  {
    label: "$fn.parserQueryParams(uri, paramName)",
    insertText: '$fn.parserQueryParams("${1:uri}", "${2:paramName}")',
    detail: "Livin query helper",
    documentation: "Parse a query parameter from URI. Registry: queryParamsParser.",
  },
  {
    label: "$fn.stringUtils()",
    insertText: "$fn.stringUtils().${1:isBlank}(${2:value})",
    detail: "Apache StringUtils class",
    documentation: "Access Apache Commons StringUtils static methods through the backend wrapper.",
  },
  {
    label: "$fn.uuid()",
    insertText: "$fn.uuid().randomUUID().toString()",
    detail: "Java UUID class",
    documentation: "Access Java UUID static methods through the backend wrapper.",
  },
  {
    label: "$fn.listHelper().emptyList()",
    insertText: "$fn.listHelper().emptyList()",
    detail: "Livin list helper",
    documentation: "Create an empty list.",
  },
  {
    label: "$fn.listHelper().sortBy(list, prop, asc)",
    insertText: '$fn.listHelper().sortBy(${1:list}, "${2:prop}", ${3:true})',
    detail: "Livin list helper",
    documentation: "Sort list of objects by property. Registry: sortingListFunction.",
  },
  {
    label: "$fn.listHelper().limitList(list, limit)",
    insertText: "$fn.listHelper().limitList(${1:list}, ${2:10})",
    detail: "Livin list helper",
    documentation: "Limit list size. Registry: limitListFunction.",
  },
  {
    label: "$fn.listHelper().addObjectToList(list, data)",
    insertText: "$fn.listHelper().addObjectToList(${1:list}, ${2:data})",
    detail: "Livin list helper",
    documentation: "Append data to a list. Registry: addObjectToList.",
  },
  {
    label: "$fn.listHelper().filterObjectList(list, key, operator, value)",
    insertText: '$fn.listHelper().filterObjectList(${1:list}, "${2:key}", "${3:eq}", "${4:value}")',
    detail: "Livin list helper",
    documentation: "Filter object list by key/operator/value. Registry: filterObjectList.",
  },
  {
    label: "$fn.listHelper().mergeList(primary, secondary, joinKey)",
    insertText: '$fn.listHelper().mergeList(${1:primaryList}, ${2:secondaryList}, "${3:joinKey}")',
    detail: "Livin list helper",
    documentation: "Merge two lists by join key. Registry: mergeList.",
  },
  {
    label: "$fn.mapHelper().map()",
    insertText: "$fn.mapHelper().map()",
    detail: "Java Map class",
    documentation: "Access Java Map class through the backend wrapper.",
  },
  {
    label: "$fn.mapHelper().listToMapSingleKey(list, keyProp)",
    insertText: '$fn.mapHelper().listToMapSingleKey(${1:list}, "${2:keyProp}")',
    detail: "Livin map helper",
    documentation: "Convert list to map using a single key. Registry: convertListToMapSingleKey.",
  },
  {
    label: "$fn.mapHelper().listToMapCompositeKey(list, keyProps)",
    insertText: "$fn.mapHelper().listToMapCompositeKey(${1:list}, ${2:keyProps})",
    detail: "Livin map helper",
    documentation: "Convert list to map using composite keys. Registry: convertListToMapCompositeKey.",
  },
  {
    label: "$fn.epochTimeHelper().formatEpoch(epochSecond, pattern)",
    insertText: '$fn.epochTimeHelper().formatEpoch(${1:epochSecond}, "${2:yyyy-MM-dd HH:mm:ss}")',
    detail: "Livin epoch helper",
    documentation: "Format epoch seconds. Registry: epochSecondConverter.",
  },
  {
    label: "$fn.epochTimeHelper().formatEpochMillis(epochMillis, pattern)",
    insertText: '$fn.epochTimeHelper().formatEpochMillis(${1:epochMillis}, "${2:yyyy-MM-dd HH:mm:ss}")',
    detail: "Livin epoch helper",
    documentation: "Format epoch milliseconds. Registry: epochMillisConverter.",
  },
  {
    label: "$fn.epochTimeHelper().toUnix(dateStr, pattern, isDateOnly)",
    insertText: '$fn.epochTimeHelper().toUnix("${1:2026-05-13}", "${2:yyyy-MM-dd}", ${3:true})',
    detail: "Livin epoch helper",
    documentation: "Convert date string to Unix epoch. Registry: unixConverter.",
  },
];

export const VTL_SNIPPET_COMPLETIONS = [
  {
    label: "#set",
    insertText: "#set($${1:var} = ${2:value})",
    detail: "Velocity directive",
    documentation: "Assign a variable.",
  },
  {
    label: "#if",
    insertText: "#if(${1:condition})\n  ${2}\n#end",
    detail: "Velocity directive",
    documentation: "Conditional block.",
  },
  {
    label: "#foreach",
    insertText: "#foreach($${1:item} in ${2:list})\n  ${3}\n#end",
    detail: "Velocity directive",
    documentation: "Loop over a collection.",
  },
  {
    label: "$!{variable}",
    insertText: "$!{${1:variable}}",
    detail: "Quiet Velocity reference",
    documentation: "Quiet reference that suppresses undefined output.",
  },
  {
    label: "${variable}",
    insertText: "${${1:variable}}",
    detail: "Velocity reference",
    documentation: "Braced reference.",
  },
];

export const LIVIN_REGISTRY_FUNCTION_NAMES = [
  "addObjectToList",
  "amountFormatter",
  "aritmaticFunction",
  "bigDecimalParser",
  "convertListToMapCompositeKey",
  "convertListToMapSingleKey",
  "convertTimestampToStringFormat",
  "currentDate",
  "currentSystemTimeMillis",
  "dateFormatConverter",
  "dateTimeFormatConverter",
  "epochConverter",
  "epochMillisConverter",
  "epochSecondConverter",
  "filterObjectList",
  "integerParser",
  "jsonToStringConverter",
  "limitListFunction",
  "localDateFunction",
  "localDateTime",
  "mergeList",
  "queryParamsParser",
  "roundingDecimal",
  "runningNumber",
  "sortingListFunction",
  "tellerId",
  "throwError",
  "timestampMillis",
  "trackingId",
  "unixConverter",
];
